name: test

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gtest
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - name: install g++-10
      run: sudo apt-get install g++-10 -y
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && export CC=/usr/bin/gcc-10 && export CXX=/usr/bin/g++-10 && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
      working-directory: test
    - name: build
      run: cmake --build .
      working-directory: test/build
    - name: run test
      run: ls && ./test
      working-directory: test/build
